runtime: python38
env: standard
entrypoint: gunicorn -b 0.0.0.0:$PORT -w 6 wsgi:app

runtime_config:
  python_version: 3

env_variables:
  FRONTEND_PATH: https://encurte.herokuapp.com
  DB_ENGINE: FireBaseDbAccess