runtime: python38
env: standard
entrypoint: gunicorn -b 0.0.0.0:$PORT -w 4 wsgi:app --timeout 120

runtime_config:
  python_version: 3

env_variables:
  FRONTEND_PATH: https://encurte.herokuapp.com/

  DB_ENGINE: FireBaseDbAccess
  CLOUD_SEND_TO_QUEUE: https://southamerica-east1-encurte.cloudfunctions.net/send_access_to_queue